name: Deploy

on:
  push:
    branches: [$default-branch]
  workflow_dispatch: {} # manual release

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Restore build cache
        uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload Pages artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          preview: ${{ github.ref_name == 'main' }}
      
      - name: Cleanup CDN Cache
        if: ${{ github.ref_name == 'main' }}
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
            -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_AUTH_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
