name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: {} # manual release

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v4

      - name: Use Node 16.x
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        id: artifact
        with:
          path: public

      - name: Zzzzz (need to sleep to get the artifact propagated)
        run: sleep 10

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        id: deployment
        with:
          preview: ${{ github.ref_name == 'main' }}
      
      - name: Cleanup CDN Cache
        if: ${{ github.ref_name == 'main' }}
        run: |
          curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE }}/purge_cache" \
            -H "X-Auth-Email: ${{ secrets.CLOUDFLARE_EMAIL }}" \
            -H "X-Auth-Key: ${{ secrets.CLOUDFLARE_AUTH_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
